name: Create and publish a Docker image to GHCR

on:
  workflow_call:
    inputs:
      path:
        type: string
        description: 'Path of the project to build'
        required: true
      packageName:
        type: string
        description: 'Name of the package to publish'
        required: true

  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag for mannually created image'
      path:
        type: string
        description: 'Path of the project to build'
        required: true
      packageName:
        type: string
        description: 'Name of the package to publish'
        required: true

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: Build and Publish Image

    permissions:
        contents: read
        packages: write
        attestations: write
        id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/eivarin/${{ inputs.packageName }}
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=raw,value=${{ github.event.inputs.tags }},enable=${{ github.event_name == 'workflow_dispatch' }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ${{ inputs.path }}/.
          file: ${{ inputs.path }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}