name: Push to main CI

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - run: |
          ls apps | xargs -I _ echo "_: apps/_" > .github/targets.txt

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: .github/targets.txt

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.prepare.outputs.packages) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get Version
        id: version
        run: echo "image_version=$(cat apps/${{ matrix.package }}/.version)" >> $GITHUB_OUTPUT
    
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/eivarin/${{ matrix.package }}
          labels: |
            org.opencontainers.image.version=${{ steps.version.outputs.image_version }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.version.outputs.image_version }}
            type=sha

      - run: cat ${{ steps.meta.outputs.bake-file }}
        name: Show bake file

      - name: Build
        uses: docker/bake-action@v6
        with:
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
          push: true
          targets: image
          set: |
            image.context=./apps/${{ matrix.package }}